version: "3.8"
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
      PUID: 1000
      PGID: 1000
      DISABLE_HOST_CHECK: "true"  # Thêm biến môi trường để tắt kiểm tra host header
    volumes:
      - ./puter/config:/etc/puter
      - ./puter/data:/var/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://puter.localhost:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    command: --host 0.0.0.0  # Thêm tham số --host để server có thể nhận các request từ tất cả các IP
