version: "3.8"
services:
  puter:
    container_name: puter
    image: ghcr.io/heyputer/puter:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - '4100:4100'
    environment:
      PUID: 1000
      PGID: 1000
      DISABLE_HOST_CHECK: "true"  # Tắt kiểm tra host header (nếu app hỗ trợ)
      HOST: "0.0.0.0"  # Cấu hình host
      PORT: "4100"  # Cấu hình port
    volumes:
      - ./puter/config:/etc/puter
      - ./puter/data:/var/puter
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:4100/test || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
